version: '3.8'

services:

  db:
    image: postgres:15-alpine
    container_name: async-practice-db
    environment:
      POSTGRES_DB: trades
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5422:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d trades"]
      interval: 10s
      timeout: 5s
      retries: 5

#  app:
#    build: .
#    container_name: async-practice-app
#    ports:
#      - "8099:8099"
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5422/trades
#      SPRING_DATASOURCE_USERNAME: user
#      SPRING_DATASOURCE_PASSWORD: password
#    depends_on:
#      db:
#        condition: service_healthy

volumes:
  postgres_data: