server:
  port: 8099

spring:
  application:
    name: async-spring-practice

  datasource:
    url: jdbc:postgresql://localhost:5422/trades
    username: ${SPRING_DATASOURCE_USERNAME:user}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

  flyway:
    baseline-on-migrate: true
