CREATE TABLE trades (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    buying_account_id BIGINT NOT NULL,
    vendor_account_id BIGINT NOT NULL,
    product_name VARCHAR(255) NOT NULL,
    product_quantity INT NOT NULL,
    product_buying_price DECIMAL(19, 2) NOT NULL,
    product_selling_price DECIMAL(19, 2) NOT NULL
);
