CREATE TABLE trades (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    buying_account_id BIGINT NOT NULL,
    selling_account_id BIGINT NOT NULL,
    product_name VARCHAR(255) NOT NULL,
    product_quantity INT NOT NULL,
    product_buying_price DECIMAL(19, 2) NOT NULL,
    product_selling_price DECIMAL(19, 2) NOT NULL,
    created_by BIGINT,
    modified_by BIGINT,
    created_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_date TIMESTAMP
);
